### ISSUE TITLE
FormatException error occurs when parsing the YAML file.

### ISSUE THREAD

**Issue by JasonHardman** [vipoo/iRacingSDK.Net#5]
FormatException error occurs when parsing the YAML file. This occurs when in a Race as a spectator and is the result of the spectators CarNumber being equal to "".

**Comment by JasonHardman** [comment]
I have uploaded a replay of a Mazda race at Limerock that was recorded as a spectator.  You can find it at :
http://1drv.ms/1DSPJIq

**Comment by vipoo** [comment]
Hi Jason,

Got your replay - planning to have a look at it today.

And thanks for the contribution to the SDK - its cool having some help

I really appreciate your involvement.

Cheers
Dean

**Comment by vipoo** [comment]
Hi Jason,

I have updated the sdk to support spectator races - (also fixed some bugs)

I believe you were originally right to suggest CarNumber be a string - I
believe this is like a display value - the CarNumberRaw is always a number.

Its interesting, that in my app - I had been mostly using CarNumberRaw for
when selecting a camera - and using CarNumber when drawing video overlay.

Let me know how it goes for you.

Cheers
Dean
